name: yanivattar
favicon: null
layout_spectrum: 0.4447959172539413
typography_spectrum: 0.8022811547853053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1696773029398173
  lightness: 0.23516672709956765
  saturation: 0.8588450469542295
  rhythmicContrast: 0.966874044155702
purpose: []
